mykey = "your_key_name"
ami = "ami-08a0d1e16fc3f61ea"
region = "us-east-1"
instance_type = "t3.xlarge"
GitLab_server_sec = "GitLab-server-sec"
GitLab-server-tag = "GitLab Server"
GitLab-profile = "GitLab-profile-tr"
GitLab-role = "GitLab-server-role"
